services:
    # Factory
    yamilovs.color_captcha.factory:
        class: Yamilovs\ColorCaptchaBundle\Manager\ColorCaptchaFactory
        arguments: ["@session"]

    # Form Type
    yamilovs.color_captcha.form_type:
        class: Yamilovs\ColorCaptchaBundle\Form\Type\ColorCaptchaType
        arguments: ["@yamilovs.color_captcha.form_type_event_subscriber"]
        tags:
            - { name: form.type }

    # Form Type Event Subscriber
    yamilovs.color_captcha.form_type_event_subscriber:
        class: Yamilovs\ColorCaptchaBundle\Form\EventListener\ColorCaptchaListener
        arguments: ["@yamilovs.color_captcha.factory", "@translator.default", "%validator.translation_domain%"]

    # Colors
    yamilovs.color_captcha.color.red:
        class: Yamilovs\ColorCaptchaBundle\Color\RedColor
        tags:
            - { name: ColorCaptchaColor, alias: red }

    yamilovs.color_captcha.color.blue:
        class: Yamilovs\ColorCaptchaBundle\Color\BlueColor
        tags:
            - { name: ColorCaptchaColor, alias: blue }

    yamilovs.color_captcha.color.green:
        class: Yamilovs\ColorCaptchaBundle\Color\GreenColor
        tags:
            - { name: ColorCaptchaColor, alias: green }

    yamilovs.color_captcha.color.grey:
        class: Yamilovs\ColorCaptchaBundle\Color\GreyColor
        tags:
            - { name: ColorCaptchaColor, alias: grey }

    yamilovs.color_captcha.color.pink:
        class: Yamilovs\ColorCaptchaBundle\Color\PinkColor
        tags:
            - { name: ColorCaptchaColor, alias: pink }

    yamilovs.color_captcha.color.yellow:
        class: Yamilovs\ColorCaptchaBundle\Color\YellowColor
        tags:
            - { name: ColorCaptchaColor, alias: yellow }
